export const CITY_ACTIONS = {
  GET_CITY_LIST: {
    LOADING: 'GET_CITY_LIST_LOADING',
    SUCCESS: 'GET_CITY_LIST_SUCCESS',
    FAILURE: 'GET_CITY_LIST_FAILURE',
  },
  SEARCH_CITY: {
    LOADING: 'GET_CITY_LIST_LOADING',
    SUCCESS: 'GET_CITY_LIST_SUCCESS',
    FAILURE: 'GET_CITY_LIST_FAILURE',
  },
  CLEAR_CITY_LIST: {
    SUCCESS: 'CLEAR_CITY_LIST_SUCCESS',
  },
};

export const WEATHER_ACTIONS = {
  GET_WEATHER_LIST: {
    LOADING: 'GET_WEATHER_LIST_LOADING',
    SUCCESS: 'GET_WEATHER_LIST_SUCCESS',
    FAILURE: 'GET_WEATHER_LIST_FAILURE',
  },
};
